version: "3.9"

services:
# --------------------------------------------------- Qdrant
  qdrant:
    image: qdrant/qdrant:v1.9.1
    ports: ["6334:6333"]  # External:Internal
    volumes: [qdrant_data_eval:/qdrant/storage]

# ---------------------------------- Backend (índices + FastAPI)
  backend:
    build: .
    depends_on: [qdrant]
    env_file: [.env]
    environment:
      QDRANT_URL: "http://qdrant:6333"
      PYTHONPATH: "/app"  # ← IMPORTANTE: Para que encuentre el módulo backend
    volumes:
      - ./datasets:/datasets
      - ./bm25_cache:/indexes    # ←─ comando directo para uvicorn
    ports: ["8001:8000"]  # External:Internal
    command: ["bash", "/app/deployment/scripts/build_and_start.sh"]  # ← Nueva ruta

# ---------------------------------- UI Streamlit
  streamlit:
    build: .
    container_name: rag-ui-eval
    depends_on: [backend]
    environment:
      API_URL: "http://backend:8000/query" 
      PYTHONPATH: "/app"  # ← Agregar también aquí
    command: >
      streamlit run frontend/ui.py
        --server.port 8501
        --server.address 0.0.0.0
    ports: ["8502:8501"]  # External:Internal

volumes:
  qdrant_data_eval:
  bm25_cache_eval:
