version: "3.9"

services:
# --------------------------------------------------- Qdrant
  qdrant:
    image: qdrant/qdrant:v1.9.1
    ports: ["6333:6333"]
    volumes: [qdrant_data:/qdrant/storage]

# ---------------------------------- Backend (índices + FastAPI)
  backend:
    build: .
    depends_on: [qdrant]
    env_file: [.env]
    environment:
      QDRANT_URL: "http://qdrant:6333"
      PYTHONPATH: "/app"  # ← IMPORTANTE: Para que encuentre el módulo backend
    volumes:
      - ./datasets:/datasets
      - ./bm25_cache:/indexes    # ←─ comando directo para uvicorn
    ports: ["8000:8000"]  # ← AGREGAR ESTA LÍNEA
    command: ["bash", "/app/deployment/scripts/build_and_start.sh"]  # ← Nueva ruta

# ---------------------------------- UI Streamlit
  streamlit:
    build: .
    container_name: rag-ui
    depends_on: [backend]
    environment:
      API_URL: "http://backend:8000/query"
      PYTHONPATH: "/app"  # ← Agregar también aquí
    command: >
      streamlit run frontend/ui.py
        --server.port 8501
        --server.address 0.0.0.0
    ports: ["8501:8501"]

volumes:
  qdrant_data:
  bm25_cache:
